<?php include("header_satellite.php"); ?>
		<span class="satellite_title">FAQs</span><br><br>
		<p><strong>Discounts: </strong>Orders will receive a 5% discount on orders under $5,000.00 or free&nbsp; shipping on orders over $5,000.00.&nbsp; Residential delivery is available for a $99.00 fee.&nbsp; We do not charge sales tax for out of state orders like other online suppliers.<strong><br /><br />How To Order:</strong>&nbsp; There are two options for placing order 1. Visit our <a class="kitchen" href="store.php" target="_blank">Online Store</a> and place your order or 2. Fill out our <a class="kitchen" href="docs/order_form.xls" target="_blank">Online Order Form</a> and email to <a class="kitchen" href="mailto:orders@onlinecabinetsdirect.com">orders@onlinecabinetsdirect.com</a> or send via Fax to 1-888-820-3066.</p>
		<p><strong>How Do I Find Your Pricing:</strong> Please visit our <a class="kitchen" href="store.php" target="_blank">Online Store</a> or <a class="kitchen" href="catalog.php" target="_blank">Catalog &amp; Pricing page.</a></p>
		<p>Are your cabinets shipped already assembled or do I have to put it together? Due to the discount pricing and the savings we offer you, our cabinets are shipped unassembled unless you have Online Cabinets Direct assemble them, the cabinets are packaged in sturdy cardboard boxes ready for assembly. For more info on cabinet construction see our specification page or email us at <a class="kitchen" href="mailto:orders@onlinecabinetsdirect.com">orders@onlinecabinetsdirect.com</a> and we can send you an assembly video.</p>
		<p><strong>Cabinet Assembly:</strong> Online Cabinets Direct does not use plastic L brackets, metal clips nor camlocks in our assembly, we use the highest grade construction method on the market today which is I-Beam construction.&nbsp; Our assembly method uses two 1/2" plywood side &amp; back panel and 4" wide strips along the top of your base cabinets which run in the top dadoes to ensures that once your cabinet is constructed it is square during installation. Unlike our competitions camlock, L bracket or metal clip assembly method cabinets which can become racked during construction and installation.</p>
		<p>Our cabinets utelize the highest standard pin and glued constrution method to ensure you will have your cabinets for many years to come.</p>
		<p>If you are not sure you would like to assemble your cabinets, Online Cabinets Direct is more than happy to assemble your cabinets for&nbsp; a fee of $30.00 per regular cabinet and $60.00 for tall cabinets.</p>
		<p><strong>Glaze On French Vanilla:</strong> Online Cabinets Direct does offer glazing on our French Vanilla Deluxe for a small fee plus assembly, our Ginger and Mocha Deluxe do come standard with black glaze.&nbsp; If you do choose to have your French Vanilla Deluxe order glazed by Online Cabinets Direct we do require the cabinets to be assembled by Online Cabinets Direct due to the cost of repacking the cabinets and risk of damage after glaze.</p>
		<p><strong>How do I assemble the cabinets?</strong>&nbsp; Assembly is required if you choose for Online Cabinets Direct not to assemble your cabinets.&nbsp; Online Cabinets Direct utelizes the most durable construction method which is I-Beam, pen and glue construction used by custom cabinet makers. If you would like more information about cabinet assembly please see our specification page, download the <a class="kitchen" href="docs/assembly_guide.pdf" target="_blank">Assembly Instruction Guide</a> or please see our <a class="kitchen"onclick="javascript:void window.open('video_player_machine.php?video_code=https://www.youtube.com/embed/LDVKh_n3CAE?rel=0&showinfo=0&autoplay=1&autohide=1','1435862141398','width=560,height=315,toolbar=0,menubar=0,location=0,status=0,scrollbars=0,resizable=1,left=50,top=100');return false;">
		Cabinet Assembly Video</a> for your reference.</p>
		<p><strong>Are your cabinets made of particle board or plywood?</strong>&nbsp;Our cabinet boxes are 1/2" plywood, we also use 1/2" hanging rails for added support. We do not offer inexpensive particle board, low quality metal clips, camlocks nor do we use plastic L brackets which commonly break during assembly which are used by many other online suppliers. Our cabinetry is made with the highest quality 1/2" plywood and is built to last.</p>
		<p><strong>What information do you need to provide a quotation on my kitchen?</strong> First, pick out a door style, then visit our our <a href="store.php" class="kitchen">Online Store</a> for pricing.&nbsp; Shipping usually ranges between $200 to $500, shipping is determined by the weight of the order and your location. If you would like for us to design your kitchen for you please email us your kitchen floor plan and we will have one of our professionals design your kitchen.&nbsp; Please call 615-828-8377 with any questions or fax your design to 615-302-8214.</p>
		<p><strong>How long will it take to receive my order once it's placed?</strong> Our distributors facility is over 100,000 square foot and has over 25,000 cabinets in stock so most orders ship within 1-3 weeks. Transit time will vary depending on your location, most shipments are usually delivered within 3 to 5 business days after being shipped from our location.</p>
		<p><strong>How do you ship the cabinetry?</strong> Our company utilizes common carrier freight lines or local pickup at our warehouse is available to customers at no additional cost.</p>
		<p><strong>How will I know when my cabinets are shipped?</strong> Once your order has shipped we will either call you or send you an email with the name of the carrier who has your shipment, their phone number of their local terminal in your area, and the shipment number for your order. You can then call your local terminal to get an exact day of delivery date for your order.</p>
		<p><strong>What if I receive damaged cabinets?</strong> Due to our extreme caution in packaging and the highly qualified freight carrier, damage is rare, but can happen. If this does happen please note on on the weigh bill from the courier that there was damage. Our cabinets are inspected before shipment, boxed and strapped on pallets for a safe secure shipment. Should you receive a damaged item, notify us at as soon as you receive the goods, take images of the damaged goods and email the images to <a href="mailto:orders@onlinecabinetsdirect.com">orders@onlinecabinetsdirect.com</a> or fax to 615-302-8214 within 72 hours of receiving the goods. Once the claim is filed with the courier, we will send you any replacement parts that were damaged once you send the damaged items back for inspection.&nbsp; Online Cabinets Direct is not responsible for damage due to the freight carrier, any item damaged during transit will be replaced with a new item and a claim will be filed with the courier service provider.</p>
		<p><strong>How much will shipping cost?</strong> Depending on your location shipping costs vary. Local pickup at our warehouse is available to customers at no additional cost. Shipping cost are usually below $20.00 per cabinet but may vary depending on weight and your location. Residential delivery and liftgate services are available for additional fees.&nbsp; Residential Delivery Fee $99.00, Liftgate Service Fee $99.00.&nbsp; We do not supply liftgate service for orders unless specified by the customer and the customer agrees to the additional fees associated with the liftgate fees from the courier.</p>
		<p><strong>Payment Options:</strong> Online Cabinets Direct accepts all major credit cards including Visa,&nbsp; Master Card, American Express and Discover Card.&nbsp; We also accept payment through Google Checkout, PayPal E-Check and PayPal.&nbsp;&nbsp;</p>
		<p><strong>Can I feel safe making this kind of purchase from you over the Internet?</strong> Many people have this concern about ordering online. Online Cabinets Direct is <a class="kitchen" href="http://www.bbb.org/nashville/business-reviews/cabinets/online-cabinets-direct-in-spring-hill-tn-37041504" target="_blank">Better Business Bureau</a> and a <a class="kitchen" href="http://www.buysafe.com/" target="_blank">BuySafe</a> cerftified supplier. We offer a secure method of payment utilizing PayPal, Google Checkout and all major credit cards or you can call us with your credit card information to place your order over the phone.&nbsp; This process is done for all transactions for the most secure transaction possible.&nbsp; Our company offers our secure shopping cart for your convenience to ensure a secure online shopping experience.</p>
		<p>Please call 615-828-8377 or email: <a href="mailto:orders@onlinecabinetsdirect.com" class="kitchen">orders@onlinecabinetsdirect.com</a> with any questions. If you need design assistance please fax your layout to 1-888-820-3066</p><br><br>
		</div>
	</div>
<?php include("footer.php"); ?>

