<?php
if($_GET['back_page']=="calendar_list")
{
$return_back_page="calendar_list.php";
}
else
{
$return_back_page="calendar_list.php?month=";
$return_back_page.=$_GET['month'];
$return_back_page.="&right_now=";
$return_back_page.=$_GET['right_now'];
}

if($_GET['back_page']=="calendar_list")
{
$post_back_page="calendar_list";
$post_back="";
$post_right_now="";
}
else
{
$post_back_page="calendar_back";
$post_back=$_GET['month'];
$post_right_now=$_GET['right_now'];
}
?>
